language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: "royopa@gmail.com"

matrix:
  fast_finish: true
